name: pintel_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  shared_preferences: ^2.3.3
  intl: ^0.18.1
  dio: ^5.7.0
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  path_provider: ^2.1.5
  image_gallery_saver_plus: ^3.0.5
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  lottie: ^3.1.3
  connectivity_plus: ^6.1.0
  introduction_screen: ^3.1.14
  date_field: ^5.3.0
  flutter_html: ^3.0.0-beta.2
  multi_dropdown: ^3.0.1
  contained_tab_bar_view: ^0.8.0
  carousel_slider: ^5.0.0
  flutter_widget_from_html_core: ^0.16.0
  syncfusion_flutter_charts: ^27.2.5
  html: ^0.15.4
  async: ^2.11.0
  flutter_native_splash: ^2.4.4
  font_awesome_flutter: ^10.8.0
  dropdown_button2: ^2.3.9
  flutter_staggered_grid_view: ^0.7.0
  dotted_line: ^3.2.3
  
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.12.0
  location: ^8.0.0
  pin_code_fields: ^8.0.1
  carousel_slider_plus: ^7.1.0
  smooth_page_indicator: ^1.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animation/
    - assets/fonts/
    - assets/icons/
    - assets/image/
    - assets/animation/
    - assets/lang/
    - assets/lottie/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Arabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Arabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Arabic-Bold.ttf
          weight: 700
